// <auto-generated />
using Api_clean_architecture.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tecnicos.Data.Migrations
{
    [DbContext(typeof(TecnicosContext))]
    partial class TecnicosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tecnicos.Data.Models.Compras", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("CompraId");

                    b.ToTable("Compras", (string)null);

                    b.HasData(
                        new
                        {
                            CompraId = 1,
                            Descripcion = "Router",
                            Monto = 250.0
                        },
                        new
                        {
                            CompraId = 2,
                            Descripcion = "Switch",
                            Monto = 150.0
                        },
                        new
                        {
                            CompraId = 3,
                            Descripcion = "Hub",
                            Monto = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
